### ISSUE TITLE
Landing page should be implemented as designs

### ISSUE THREAD

**Issue by orlando** [debtcollective/membership#1]
**What:** Landing page should be implemented as designs

**How:**

- Using a CSS framework implement designs to be rendered by Rails.

**Notes**:

- Designs are not final yet, I'll update this ticket with links once it's done

**Comment by orlando** [comment]
Designs are ready but are not on Figma yet. We reviewed the designs with devs and we are working with the source file atm

**Comment by castrolem** [comment]
@orlando We'll need the logo asset with a @2x resolution (both "collective" colors aka, black/white), or as an SVG.

**Comment by castrolem** [comment]
@orlando When can we have a mobile view of the designs?
