### ISSUE TITLE
Design enhancements

### ISSUE THREAD

**Issue by orlando** [debtcollective/membership#118]
**What**: Design enhancements.

**Why**: The height of the sections and the text size are not in the right proportion, we are dedicating a lot of vertical space just to show an image an a bit of text. The idea is to reduce this because it will affect both Desktop devices that have a big screen and small mobile devices.

**How**:

- Reduce the height of the sections, we don't need to make all sections to have 100vh of height.
- Improve "Where is your money going?" and "What are we fighting for?" readability by making text bigger and changing the backdrop to be dark instead of white.
- Make the shop section more appealing for users to click on

**Comment by castrolem** [comment]
@orlando are we adding photos from the actual store into the store then?
Could you send me the link to the current store and 3 articles that would be nice to feature?

**Comment by orlando** [comment]
@castrolem this is the store https://teespring.com/stores/debt-collective. You can either have photos or the products embedded, whatever works best
