### ISSUE TITLE
User should be able to pick a subscription plan

### ISSUE THREAD

**Issue by orlando** [debtcollective/membership#14]
**What:** User should be able to pick a subscription plan

User can choose from different donation tiers.

**How:**

- User can choose from different donation tiers.
- User can only choose one donation tier.

**Comment by castrolem** [comment]
@orlando isn't this a duplicate of #13 ?

**Comment by orlando** [comment]
@castrolem just to have the feature that we will have multiple plans in another ticket. A PR can close both
