### ISSUE TITLE
User should be able to upgrade/downgrade their subscription

### ISSUE THREAD

**Issue by orlando** [debtcollective/membership#22]
**What:** User should be able to upgrade/downgrade their subscription

**Why:** For users to increase or decrease their contribution without admin intervention

**How:**

In the Subscription section in the back-office, User will see a Change Subscription button, similar to What Netlify does

![image](https://user-images.githubusercontent.com/849872/66940664-f575fb80-f00a-11e9-8aaf-f2825cea686d.png)

When clicking **Change Plan**, it shows a list of plans with their description, just like we do in the home page. The users pick a plan and then the system schedules the upgrade to be done in the next billing cycle.

### Implementation recomendations

- When the user changes their plan, either doing an upgrade or downgrade, we store this change in a database table and schedule it for the next billing cycle.
- When the charge job runs in Sidekiq, first it will check if there's a pending plan change, if that's the case, it will do the change first instead of charging the current plan.
- If there's no pending change, just charge the current plan amount

**Comment by castrolem** [comment]
@orlando let's discuss how do we want the user experience to look like when doing these operations.

**Comment by orlando** [comment]
@castrolem I left some comments, let's have a call to discuss.

**Comment by castrolem** [comment]
I just finished the UI and specs for the basic endpoints, just need to write the logic for the actual plan change and charge.
