### ISSUE TITLE
Guest should be able to do a one time donation

### ISSUE THREAD

**Issue by orlando** [debtcollective/membership#9]
**What:** Guest should be able to do a one-time donation

**Why:** To allow people to donate anonymously

**How:**

- Save all the data we can from a user, this should include:
  - All required data by Stripe, including email address
  - User IP address
- Guest should be able to donate without creating an account

**Comment by castrolem** [comment]
@orlando we can discuss how we're going to store the user data in this scenario.
the User IP address can be accessed through rack with `request. remote_ip` and then saved into the Donation object, but the stripe user data, maybe we create a json field that contains stripe attrs? What's your opinion?

**Comment by orlando** [comment]
@castrolem yes, we can have a metadata JSONB field to store these things, validating using JSON schema
